name: crystalshards
type: Deployment
registry_user: jwaldrip
secrets:
  github.user: {{ env.GITHUB_USER }}
  github.key: {{ env.GITHUB_KEY }}
env:
  GITHUB_USER:
    secret: github.user
  GITHUB_KEY:
    secret: github.key
clusters:
  default:
    context: gke_waldrip-net_us-central1-a_waldrip-net
ingress:
  tls: true
  host: crystalshards.org
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
healthcheck: true
ports:
  http: 3000
