version: '2'

services:
  web:
    build: .
    image: crystalshards.org
    command: 'amber watch'
    working_dir: /app/user
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/crystalshards.org_development
      SMTP_URL: mail:1025
    ports:
      - '3000:3000'
    depends_on:
      - db
      - mail
    volumes:
      - '.:/app/user'

  mail:
    image: drujensen/mailcatcher:latest
    ports:
      - '1025:1025'
      - '1080:1080'

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crystalshards.org_development
    volumes:
      - 'db:/var/lib/postgres/data'

volumes:
  db:
